---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
#for server
#regions <- read_csv("2_B01_annotation_coords.csv") # base R would use read.csv
#for Catherine Mac
regions <- read_csv("../data/2_B01_annotation_coords_2019-08-5.csv")
```

```{r}
regions
```

Here is the "tidyverse" way of counting the number of each pattern.

```{r}
pattern_counts <- regions %>% 
  filter(region != "CCS") %>%
  arrange(ZMW, start) %>%
  group_by(ZMW) %>%
  summarise(pattern = paste(region, collapse = " ")) %>%
  count(pattern) %>%
  arrange(desc(n))
```

```{r}
pattern_counts
```
```{r}
# for server
write_csv(pattern_counts, "/tier2/deweylab/scratch/ipsc_pacbio/demultiplexing/profile_hmm/annotated_ccs/2_B01_annotationRegionCombos.csv")
#for Catherine Mac
#write_csv(pattern_counts,"../2_B01_annotationRegionCombos.csv")
```

Here is the "base R" way of doing the above.

```{r}
regions_no_ccs <- regions[regions$region != "CCS",]
sorted_regions_no_ccs <- regions_no_ccs[order(regions_no_ccs$ZMW, regions_no_ccs$start),]
patterns <- tapply(sorted_regions_no_ccs$region,
                   sorted_regions_no_ccs$ZMW,
                   paste,
                   collapse = " ")
pattern_counts_base <- as.data.frame(table(patterns))
pattern_counts_base_sorted <- pattern_counts_base[order(pattern_counts_base$Freq, decreasing = TRUE),]
```

